### ISSUE TITLE
Test alias (kaocha) not running

### ISSUE THREAD

**Issue by p14n** [vouch-opensource/tools.deps-build#2]
Hi,

My test is not running and I wondered if you could help or point me in the right direction.  The workflow run is here:
https://github.com/p14n/lets-record/runs/577199527?check_suite_focus=true

Using the workflow definition:
```
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: vouch-opensource/tools.deps-build@1.0.1
        with:
          alias: test
```
And deps.edn
```
:test
             {:extra-paths ["test"]
              :extra-deps {lambdaisland/kaocha {:mvn/version "1.0-612"}}
              :main-opts ["-m" "kaocha.runner"]}
```
When used locally, I get this result:
```
clojure -Atest
[(..)]
1 tests, 2 assertions, 0 failures.
```
But in the workflow
```
Run vouch-opensource/tools.deps-build@1.0.1
/usr/bin/docker run --name d00b33e9487ccce2a645a7bb2eb44851e1c6aa_e0a264 --label d00b33 --workdir /github/workspace --rm -e INPUT_ALIAS -e INPUT_JAVA-OPTS -e INPUT_SSH-KEY -e INPUT_WORKING-DIRECTORY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/lets-record/lets-record":"/github/workspace" d00b33:e9487ccce2a645a7bb2eb44851e1c6aa  "test" "" "" ""
+ clojure -Atest
Clojure 1.10.1
user=> 
```

Any help appreciated

**Comment by stijnopheide** [comment]
Hi @p14n, 

In your github workflow, generally you first want to checkout the code of the repo before you run any other action.

An example:

```yaml
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vouch-opensource/tools.deps-build@1.0.1
        with:
          alias: test
```

I hope this solves your issue.
